<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="EFCore.NamingConventions" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
        <PackageReference Include="Npgsql.OpenTelemetry"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\WhatsEnvio.Core\WhatsEnvio.Core.csproj" />
      <ProjectReference Include="..\WhatsEnvio.Modules.Identity.Application\WhatsEnvio.Modules.Identity.Application.csproj" />
      <ProjectReference Include="..\WhatsEnvio.Modules.Identity.Domain\WhatsEnvio.Modules.Identity.Domain.csproj" />
    </ItemGroup>

</Project>
