<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\WhatsEnvio.Core\WhatsEnvio.Core.csproj" />
      <ProjectReference Include="..\WhatsEnvio.Modules.Identity.Contracts\WhatsEnvio.Modules.Identity.Contracts.csproj" />
      <ProjectReference Include="..\WhatsEnvio.Modules.Identity.Domain\WhatsEnvio.Modules.Identity.Domain.csproj" />
    </ItemGroup>

</Project>
