name: whatsenvio

services:
  postgres:
    image: postgres:18.4-alpine3.23
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  api:
    build:
      context: ../..
      dockerfile: src/WhatsEnvio.Api/Dockerfile
    environment:
        ConnectionStrings__WhatsEnvio: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "127.0.0.1:${API_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy

  worker:
    build:
      context: ../..
      dockerfile: src/WhatsEnvio.Worker/Dockerfile
    environment:
        ConnectionStrings__WhatsEnvio: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres-data:

