<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="EFCore.NamingConventions" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
        <PackageReference Include="Npgsql.OpenTelemetry"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\WhatsEnvio.Core\WhatsEnvio.Core.csproj" />
        <ProjectReference Include="..\WhatsEnvio.Modules.Tenancy.Application\WhatsEnvio.Modules.Tenancy.Application.csproj" />
        <ProjectReference Include="..\WhatsEnvio.Modules.Tenancy.Domain\WhatsEnvio.Modules.Tenancy.Domain.csproj" />
    </ItemGroup>

</Project>
